"""Independent complete-file cost diagnostic receiver; never qualification.

The caller supplies externally obtained inventory and retired-unit evidence.
Whole bytes are authenticated before records/packets are decoded. Matching
invented anchors is not independent capture-origin or driver-code evidence.
"""
from hashlib import sha256
from pathlib import Path
import re

from mjlab_microduck import stance_solver_replay_receiver as old
from mjlab_microduck import stance_solver_cost_probe as probe
from mjlab_microduck import stance_solver_cost_binary as binary
from mjlab_microduck import stance_solver_cost_dispatch as dispatch
from mjlab_microduck import stance_solver_cost_executable as executable
from mjlab_microduck import stance_solver_cost_stages as stages
from mjlab_microduck import stance_solver_scratch as scratch

PROTOCOL = "microduck-caller-cost-receiver-oct9-v1"
need = old.need


def _json(raw, label):
    value = old._json(raw, label)
    need(old._canonical(value) == raw, "canonical JSON record " + label)
    return value


def _artifact(raw, inventory, row, root):
    need(type(row) is dict and set(row) == {"path", "bytes", "sha256", "identity"}, "whole generated file anchor")
    p = Path(row["path"])
    need(p.is_absolute() and str(p) == row["path"] and p.is_relative_to(root), "contained native generated path")
    name = str(p.relative_to(root))
    need(name in raw and inventory[name] == {k: row[k] for k in ("bytes", "sha256")}, "generated bytes match whole inventory")
    need(type(row["identity"]) is list and len(row["identity"]) == 5
         and all(type(x) is int and x > 0 for x in row["identity"][:2]), "observed generated inode identity")
    return raw[name]


def _retirement(closeout, dcl, inventory):
    need(type(closeout) is dict and set(closeout) == {"source", "declaration_sha256", "inventory_sha256", "service", "cgroup"}
         and closeout["source"] == dcl["source"] and closeout["declaration_sha256"] == sha256(old._canonical(dcl)).hexdigest()
         and closeout["inventory_sha256"] == sha256(old._canonical(inventory)).hexdigest(), "external closeout binds exact source/declaration/inventory")
    s, original = closeout["service"], dcl["service"]
    need(type(s) is dict and all(s.get(k) == v for k, v in probe.UNIT_CAPS.items())
         and s.get("Id") == original["Id"] and s.get("InvocationID") == original["InvocationID"]
         and s.get("MainPID") == "0" and s.get("ExecMainStatus") == "0" and s.get("Result") == "success"
         and s.get("ControlGroup") == ""
         and (s.get("ActiveState"), s.get("SubState")) in (("inactive", "dead"), ("active", "exited")),
         "same successful externally retired capped unit with no main process")
    c = closeout["cgroup"]
    need(type(c) is dict and set(c) == {"path", "absent", "observed_pids"}
         and c["path"] == original["ControlGroup"] and c["absent"] is True and c["observed_pids"] == [],
         "external owned cgroup no longer exists")


def receive(root, inventory, closeout, packet):
    raw = old.authenticate(root, inventory)  # all leaves/hash checks precede all decode
    need(set(("receipt.json", "declaration.json", "supervision.json", "telemetry.json", "child.log")) <= set(raw)
         and "failure.json" not in raw, "complete successful diagnostic envelope")
    receipt, dcl = _json(raw["receipt.json"], "receipt"), _json(raw["declaration.json"], "declaration")
    need(set(receipt) == {"protocol", "source", "declaration_sha256", "owner_pid", "child_pid", "native_root", "device", "modules", "arms", "flags"}
         and receipt["protocol"] == dcl.get("protocol") == probe.PROTOCOL and receipt["flags"] == dcl.get("flags") == stages.FLAGS,
         "closed new protocol with all qualification flags false")
    source = receipt["source"]
    need(type(source) is str and re.fullmatch(r"[0-9a-f]{40}", source)
         and dcl.get("source") == source and receipt["declaration_sha256"] == sha256(raw["declaration.json"]).hexdigest(),
         "same source and whole declaration hash")
    native_root = probe.ROOT / "artifacts/evaluations" / ("caller-cost-" + source[:12])
    need(receipt["native_root"] == dcl.get("native_root") == str(native_root)
         and type(receipt["owner_pid"]) is int and type(receipt["child_pid"]) is int
         and 0 < receipt["owner_pid"] != receipt["child_pid"] > 0 and receipt["owner_pid"] == dcl.get("owner_pid"),
         "same native output and distinct owner/child identities")
    device = receipt["device"]
    need(type(device) is dict and set(device) == {"alias", "arch", "context", "object_id", "gpu_uuid"}
         and device["alias"] == "cuda:0" and type(device["arch"]) is int and device["arch"] == 120
         and device["gpu_uuid"] == probe.shared.GPU
         and all(type(device[k]) is int and device[k] > 0 for k in ("context", "object_id")), "literal native device identity")
    old._check_runtime(dcl.get("runtime"))
    need(dcl.get("bounds") == probe.BOUNDS and dcl.get("replay_input") == probe.retained.INPUT
         and dcl.get("control") == stages.control_manifest() and dcl.get("exclusive_gpu_claimed") is False,
         "unchanged bounds/domain input/control/shared lane")
    service = dcl["service"]
    need(service.get("name") == service.get("Id") == probe.unit(source)
         and service.get("MainPID") == str(receipt["owner_pid"]) and service.get("ActiveState") == "active"
         and all(service.get(k) == v for k, v in probe.UNIT_CAPS.items())
         and service.get("ControlGroup") == probe.retained.CGROUP_PARENT + probe.unit(source), "declared capped owner unit")
    src = dcl.get("source_binding")
    need(type(src) is dict and src.get("source") == source and src.get("branch") == probe.BRANCH
         and type(src.get("leaves")) is list and src["leaves"], "committed source inventory declaration")
    old._check_supervision(raw, receipt)
    _retirement(closeout, dcl, inventory)
    telemetry = _json(raw["telemetry.json"], "telemetry")
    need(telemetry.get("flags") == stages.FLAGS and type(telemetry.get("samples")) is list
         and 0 < len(telemetry["samples"]) <= 1024, "bounded retained shared telemetry")
    for sample in [dcl["baseline"], *telemetry["samples"]]:
        probe.shared.capacity(sample, dcl["baseline"])
    modules = receipt["modules"]
    need(type(modules) is dict and set(modules) == set(executable.GROUPS), "three exact compiled module records")
    observed = {}
    for role, names in executable.GROUPS.items():
        m = modules[role]
        need(type(m) is dict and set(m) == {"protocol", "role", "generated", "module_hash", "offline_disassembly", "explicit_load", "bindings", "flags",
            "loaded_binary_bytes_observed", "driver_jit_machine_code_observed", "actual_dispatch_observed"}
            and m["protocol"] == executable.PROTOCOL and m["role"] == role and m["flags"] == stages.FLAGS
            and all(m[k] is False for k in ("loaded_binary_bytes_observed", "driver_jit_machine_code_observed", "actual_dispatch_observed")),
            "closed observed executable record without driver claims")
        need(set(m["generated"]) == {"binary", "metadata", "source"}
             and set(m["offline_disassembly"]) == set(m["bindings"]) == set(names), "closed role artifact/entry sets")
        content = {n: _artifact(raw, inventory, row, native_root) for n, row in m["generated"].items()}
        need(all(Path(row["path"]).parent == native_root / ("compiled-" + role) for row in m["generated"].values()), "same role directories")
        load = m["explicit_load"]
        need(load.get("binary_path") == m["generated"]["binary"]["path"]
             and load.get("metadata_path") == m["generated"]["metadata"]["path"]
             and load.get("output_arch") == 120 and load.get("block_dim") == 256
             and load.get("returned_executable_is_cache_entry") is True
             and load.get("device_object_id") == device["object_id"], "exact observed explicit loader paths/context")
        meta = old._json(content["metadata"], "metadata")
        for n in names:
            b = m["bindings"][n]
            need(b.get("artifact_format") == "cubin" and b.get("binary_path") == load["binary_path"]
                 and b.get("metadata_path") == load["metadata_path"]
                 and b.get("binary_sha256") == sha256(content["binary"]).hexdigest()
                 and b.get("metadata_sha256") == sha256(content["metadata"]).hexdigest()
                 and b.get("module_hash") == m["module_hash"] and b.get("context") == device["context"]
                 and b.get("device") == device["alias"] and b.get("device_arch") == 120 and b.get("block_dim") == 256
                 and b.get("observed_object_ids", {}).get("module") == load.get("module_object_id")
                 and b.get("observed_object_ids", {}).get("executable") == load.get("executable_object_id")
                 and b.get("observed_object_ids", {}).get("device") == device["object_id"]
                 and type(b.get("forward_handle")) is int and b["forward_handle"] > 0
                 and type(b.get("module_handle")) is int and b["module_handle"] > 0
                 and meta.get(b["symbol"] + "_smem_bytes") == b.get("forward_smem_bytes"), "same observed entry-point byte/module bindings")
            need(n + ".sass" in raw and raw.get(n + ".stderr") == b"", "retained joined tool output")
            checked = binary.verify_disassembly(content["binary"], raw[n + ".sass"], n, b["symbol"])
            need(checked == m["offline_disassembly"][n], "independently reproduced exact offline function span")
            observed[n] = b
    need(len({modules[r]["explicit_load"]["module_object_id"] for r in modules}) == 3, "three distinct actual modules")
    arms, anchors, packets = receipt["arms"], {}, {}
    need(type(arms) is dict and set(arms) == {"reference", "control"}, "two exact caller arms")
    need(type(packet) is scratch.DecodedPacket and packet._sealed is True, "external authenticated historical packet")
    for arm in arms:
        need(type(arms[arm]) is dict and set(arms[arm]) == {"observer", "scratch"}, "closed arm restoration and observation")
        need(arms[arm]["scratch"] == dict(protocol=scratch.PROTOCOL,
            decision="dense-solver-scratch-restored-no-dispatch-or-qualification",
            source_sha256=packet.sha256, source_bytes=len(packet.raw), restored_fields=list(scratch.RESTORE_ORDER),
            retained_source_bytes=True, solver_called=False, forward_called=False, flags=dict(scratch.FLAGS)),
            "same complete authenticated original restoration in both arms")
        o = arms[arm]["observer"]
        need(o.get("protocol") == dispatch.PROTOCOL and o.get("base") == dispatch.BASE
             and o.get("caller") == "_update_constraint" and o.get("track_changes") is False
             and o.get("observed_stages") == list(stages.STAGES) and o.get("call_site_lines") == [2156, 2180, 2197, 2214]
             and o.get("call_sites_observed") is True and o.get("timing_changed_by_readback") is True
             and o.get("bindings") == observed and o.get("qualification") == stages.FLAGS
             and all(o.get(k) is False for k in ("explicit_load_provenance_authenticated", "native_gpu_execution_authenticated",
                 "capture_origin_authenticated", "external_unit_retirement_authenticated")), "same complete observed four-stage caller graph")
        c = o["capture"]
        need(c.get("protocol") == stages.PROTOCOL and c.get("stages") == list(stages.STAGES)
             and c.get("timing_changed_by_readback") is True and c.get("qualification") == stages.FLAGS
             and set(c["packets"]) == set(stages.PHASES), "complete caller capture anchors")
        packets[arm], anchors[arm] = {}, {}
        for phase in stages.PHASES:
            name = arm + "-" + phase + ".bin"
            need(name in raw and c["packets"][phase] == inventory[name], "whole raw packet matches observed boundary anchor")
            packets[arm][phase], anchors[arm][phase] = raw[name], inventory[name]
    result = stages.receive_banks(packets, anchors, packet)
    return dict(protocol=PROTOCOL, source=source, decision="two-arm-four-stage-native-diagnostic-received-not-qualification",
                artifact_files=len(inventory), artifact_bytes=sum(v["bytes"] for v in inventory.values()),
                inventory_sha256=sha256(old._canonical(inventory)).hexdigest(), banks=result,
                external_retirement_evidence_checked=True, timing_changed_by_readback=True,
                driver_loaded_bytes_observed=False, runtime_cause_proven=False, qualification=dict(stages.FLAGS))
